//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionareHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.Rezervations = new HashSet<Rezervation>();
        }
    
        public int ID { get; set; }
        public string Denumire { get; set; }
        public string Descriere { get; set; }
        public int NumarCamere { get; set; }
        public int NumarPersoane { get; set; }
        public byte[] Imagine { get; set; }
        public decimal Pret { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervation> Rezervations { get; set; }
    }
}
