//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionareHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public int Id_room { get; set; }
        public string Denumire { get; set; }
        public string Descriere { get; set; }
        public int NumarCamere { get; set; }
        public int NumarPersoane { get; set; }
        public byte[] Imagine { get; set; }
        public decimal Pret { get; set; }
    }
}
